### ISSUE TITLE
Ambiguity if a function with the same name as a record field is in scope

### ISSUE THREAD

**Issue by kozross** [ndmitchell/record-dot-preprocessor#31]
Given a source file as so:

```haskell
module RDPBlowup where

newtype Foo = Foo { id :: Int }
```

And a Cabal file as so:

```
cabal-version: 2.2
name:          rdp-blowup
version:       2.0.0
build-type:    Simple
tested-with:   GHC ==8.8.3

library
  exposed-modules:    RDPBlowup
  build-depends:
    , base                     >=4.13  && <5
    , record-dot-preprocessor  ^>=0.2.5
    , record-hasfield          ^>=1.0

  ghc-options:
    -Wincomplete-record-updates -fplugin=RecordDotPreprocessor

  hs-source-dirs:     src
  default-extensions:
    DataKinds
    DuplicateRecordFields
    FlexibleContexts
    FlexibleInstances
    MultiParamTypeClasses
    TypeApplications
    TypeSynonymInstances

  default-language:   Haskell2010
```

Attempting to compile triggers an ambiguity error:

```
[1 of 1] Compiling RDPBlowup

/home/koz/mlabs/rdp-blowup/src/RDPBlowup.hs:1:1: error:
    Ambiguous occurrence ‘id’
    It could refer to
       either ‘Prelude.id’,
              imported from ‘Prelude’ at src/RDPBlowup.hs:1:8-16
              (and originally defined in ‘GHC.Base’)
           or the field ‘id’, defined at src/RDPBlowup.hs:3:21
  |
1 | module RDPBlowup where
  | ^

/home/koz/mlabs/rdp-blowup/src/RDPBlowup.hs:1:1: error:
    Ambiguous occurrence ‘id’
    It could refer to
       either ‘Prelude.id’,
              imported from ‘Prelude’ at src/RDPBlowup.hs:1:8-16
              (and originally defined in ‘GHC.Base’)
           or the field ‘id’, defined at src/RDPBlowup.hs:3:21
  |
1 | module RDPBlowup where
  | ^
```

The module compiles fine without the plugin being enabled.

**Comment by ndmitchell** [comment]
At the moment I generate `\x r -> r{id=x}` and that clashes. To avoid the clash, I'd need to generate `\x r -> case r of Foo{id=_} -> Foo{id=r}`. Generating that for an ADT with multiple matches gets us to #30 - so suggest we figure out what that should do, the generating the right pattern isn't too hard (potentially a little verbose - but it's a generator so not worried about that).

**Comment by ndmitchell** [comment]
I fixed this by expanding everything out.

**Comment by ndmitchell** [comment]
Fixed in 0.2.6

**Comment by kozross** [comment]
Thanks for the fix!

**Comment by arjunkathuria** [comment]
Pardon the necrobump but i seem to be running into this on `v0.2.16` using the plugin. ( GHC 9.2.8 - linux-86_64 )

Ran into it on a bigger project where any data-type with a record-field named `error` would throw the ambiguity error.
I made a new minimal throw-away example to rule out any project specific effects and the behavior is same on the new example.

### Example code 

```haskell
{-# LANGUAGE DuplicateRecordFields, TypeApplications, FlexibleContexts, DataKinds, MultiParamTypeClasses, TypeSynonymInstances, FlexibleInstances, UndecidableInstances, GADTs #-}

{-# OPTIONS_GHC -fplugin=RecordDotPreprocessor #-}

module Main where

data Hi = Hi {
  name :: String,
  id :: Int,
  okay :: Int,
  error :: String
  };

main :: IO ()
main = putStrLn "Hello, Haskell!"
```

### The result
On compiling / doing a cabal-run, only the `id` and `error` fields, which have similarly named functions in Prelude, error out.

![image](https://github.com/ndmitchell/record-dot-preprocessor/assets/12858057/8280b86a-de5d-4a49-8c34-9dfa2368586b)

- If i remove those fields, it compiles fine, add anyone of them back, same error.
- If i remove `{-# OPTIONS_GHC -fplugin=RecordDotPreprocessor #-}`, while keeping those fields, it also compiles and runs fine, add this back, same error.

Did something change in 0.2.16 @ndmitchell ? Am i missing something here?

Are we supposed to use the inbuilt `RecordDotSyntax` in GHC 9.2.8 ( i think it's the first version that shipped with it ) instead of this plugin now?


#### Appendix (additional info)

Cabal file contents for completeness

```
-- Extra doc files to be distributed with the package, such as a CHANGELOG or a README.
extra-doc-files:    CHANGELOG.md

-- Extra source files to be distributed with the package, such as examples, or a tutorial module.
-- extra-source-files:

common warnings
    ghc-options: -Wall

executable rdp-blow
    -- Import common warning flags.
    import:           warnings

    -- .hs or .lhs file containing the Main module.
    main-is:          Main.hs

    -- Modules included in this executable, other than Main.
    -- other-modules:

    -- LANGUAGE extensions used by modules in this package.
    -- other-extensions:

    -- Other library packages from which modules are imported.
    build-depends:    base ^>=4.16.4.0
                    , record-dot-preprocessor == 0.2.16
                    , record-hasfield

    -- Directories containing source files.
    hs-source-dirs:   app

    -- Base language which the package is written in.
    default-language: Haskell2010
```

edit: syntax-highlighting on the code

**Comment by arjunkathuria** [comment]
Hey @ndmitchell , would love your opinion on this! 

cc: @edsko
